grammar org.example.domainmodel.Domainmodel with
                                      org.eclipse.xtext.xbase.Xbase

generate domainmodel "http://www.example.org/domainmodel/Domainmodel"

Domainmodel :
    importSection=XImportSection?
    elements+=AbstractElement*;

AbstractElement:
    PackageDeclaration | Entity  ;
JvmWildcardTypeReference:
        {JvmWildcardTypeReference} '?' (
          constraints+=JvmUpperBound (constraints+=JvmUpperBoundAnded)*
        | constraints+=JvmLowerBound (constraints+=JvmLowerBoundAnded)*
        )?;
terminal 5name : 'asda ' ;
<caret>