grammar org.eclipse.xtext.xbase.Xtype hidden(WS, ML_COMMENT, SL_COMMENT)



Domainmodel:
    importSection=XImportSection?
    elements+=AbstractElement*;

AbstractElement:
    PackageDeclaration | Entity;

PackageDeclaration:
    'package' name=QualifiedName '{'
        elements+=AbstractElement*
    '}';

Entity:
    'entity' name=ValidID ('extends' superType=JvmTypeReference)? '{'
        features+=Feature*
    '}';

Feature:
    Property | Operation;

Property:
    name=ValidID ':' type=JvmTypeReference;

Operation:
    'op' name=ValidID
        '('(params+=FullJvmFormalParameter
        (',' params+=FullJvmFormalParameter)*)?')'
        ':' type=JvmTypeReference
    body=XBlockExpression;

enum ChangeKind:
    ADD | MOVE | REMOVE;

enum ChangeKind2:
    ADD = 'add' | ADD = '+' |
    MOVE = 'move' | MOVE = '->' |
    REMOVE = 'remove' | REMOVE = '-';



myNewRef : asd super=[Operation];
myNewRef2 : '2' super=[Entity|WS];
myNewRef3 : '3a' super=[Entity|blabla];
terminal ID:
	'^'? ('a'..'z'|'A'..'Z'|'$'|'_') ('a'..'z'|'A'..'Z'|'$'|'_'|'0'..'9')*;

terminal ML_COMMENT: '/*' -> '*/';

terminal NEG : !'1a';

terminal WS: (' '|'\t'|/* this is comment */'\r'|'\n')+;

terminal ANY_OTHER: .;


terminal WITH_REF : (' '|'\t'|'\r'|'\n') STRING  . ;