grammar org.xtext.example.simple.Simple with Terminals

import "http://www.xtext.org/example/simple/Simple"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore
Model:
	elements+=AbstractElement+;
AbstractElement: Chel | Ziv ";";
Chel: "chel" {Z} Fam ;

Fam: "[" mama=[Chel] papa=[AbstractElement] "]";

Ziv: "ziv" ({R.l=current} "d" Fam)* ("sas" {R.l=current} Fam ) (Fam Fam | Fam Fam | Fam) ("sas" {R.l=current} Fam? Fam ) (f=Fam "sas" {R.l=current} Fam? Fam ) (f=Fam {R.l=current} Fam+|Fam);

