/*******************************************************************************
 * Copyright (c) 2010, 2017 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/

grammar org.eclipse.xtext.xbase.Xtype hidden(WS, ML_COMMENT, SL_COMMENT)

import "http://www.eclipse.org/xtext/xbase/Xtype"
import "http://www.eclipse.org/xtext/common/JavaVMTypes"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore


JvmTypeReference:
	JvmParameterizedTypeReference =>({JvmGenericArrayTypeReference.componentType=current} ArrayBrackets)*
	| XFunctionTypeRef;
	JvmArgumentTypeReference returns JvmTypeReference:
    	JvmTypeReference | JvmWildcardTypeReference;
/*******************************************************************************
 A
 V
 BSD

 *******************************************************************************/
 <caret>

    JvmWildcardTypeReference:
    	{JvmWildcardTypeReference} '?' (
    	  constraints+=JvmUpperBound (constraints+=JvmUpperBoundAnded)*
    	| constraints+=JvmLowerBound (constraints+=JvmLowerBoundAnded)*
    	)?;
